version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - appnet

  frontend:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    restart: always
    networks:
      - appnet

networks:
  appnet:
